openapi: 3.0.0
info:
  title: Advocate registry
  description: |
    This document houses API specifications for an advocate registry. For V1, we are capturing only the advocate's contact details + bar number. Eventually, this registry should integrate with a central advocate registry and sync details from there.
  version: 1.0.0
tags:
  - name: Advocate
    description: APIs to capture advocate or legal representative information
paths:
  /advocate/v1/_create:
    post:
      tags:
        - Advocate
      summary: Register a new advocate
      description: |
        API to register a new advocate in the system
      requestBody:
        description: Details for the advocate registration + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with advocate info updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateResponse'
        '400':
          description: Advocate(s) registration failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /advocate/v1/_update:
    post:
      tags:
        - Advocate
      summary: Update advocate requests
      requestBody:
        description: Details of the registered advocate + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CourtCaseRequest
        required: true
      responses:
        '201':
          description: ReponseInfo with advocate data updated successfully
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CourtCaseResponse
        '400':
          description: Advocate updation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
      
components:
  schemas:
    Advocate:
      type: object
      required: [tenantId, userId]
      properties:
        id:
          type: string
          description: autogenerated id of the case. It is the primary key.
          minLength: 2
          maxLength: 64
          readOnly: true
        tenantId:
          type: string
          description: The tenant where this case is operational
        barNumber:
          type: string
          description: Unique bar number assigned to a practicing advocate
          minLength: 2
          maxLength: 64
        userId:
          type: string
          description: >-
            The user ID (User registry) of the advocate containing all their
            details.
        isActive:
          type: boolean
          description: >-
            Field used for soft delete of records. Will be false if this entity
            is not active within the system.
          default: true
        documents:
          type: array
          description: >-
            This can be used to store any relevant documents related to the advocate's practice.
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any extra fields that are not captured as first class fields can be
            stored here as key/value pairs. Implementation specific.
    AdvocateRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Advocate'
    AdvocateResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Advocate'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
    