openapi: "3.0.2"

info:
  title: API specs for Application
  description:
    Application API paths and entity is defined in this file.
  version: "1.0.0"

servers:
  - url: https://api.server.test/v1

tags:
  - name: Application
    description: APIs for managing Application related to a Case

paths:
  /test:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    ApplicationRequest:
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo'
        application:
          $ref: '#/components/schemas/Application'

    ApplicationResponse:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo'
        application:
          $ref: '#/components/schemas/Application'

    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: auto generated primary for internal reference
          readOnly: true
        caseId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: the associated case
        createdDate:
          type: string
          format: date
          description: the date on which the order was created. Can be treated as the start date also
        createdBy:
          type: string
          format: uuid
          description: ID of the person (lawyer) who created the application
        onBehalfOf:
          type: array
          items:
            type: string
            format: uuid
            description: ID of the users for whom the application has been raised
        applicationType:
          type: string
          description: Master Data ID
        applicationNumber:
          type: string
          minLength: 24
          maxLength: 48
          description: number assigned to the application. applications are numbered serially for the court and affixed with the year.
          example: Application 1 of the year 2024
        status:
          type: string
          description: workflow status
        documents:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document'
        additionalDetails:
          type: string
          description: This field is meant to hold any extra information that we want to store.
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails'
        workflow:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow'