openapi: 3.0.0
info:
  title: CaseManagementService APIs
  description: |
    1. CaseManagement - These APIs work with the underlying Case registry and deal with the procedural details (workflow and other business logic) associated with filing a case. 
    2. Witness - APIs to map and unmap witnesses to a case. Witnesses are added initially during case filing time and can be continually modified throughout the case lifecycle. 
  version: 1.0.0
tags:
  - name: CaseManagementService
    description: APIs related to case management attributes. 
  - name: Witness
    description: >-
      APIs to add/remove witness to a case. A case can be created without
      witnesses. Witnesses can be added to the case at the beginning or onlthe
      fly.
paths:
  /casemanagement/v1/_create:
    post:
      tags:
        - CaseManagementService
      summary: Create new case .
      description: |
        To create new case in the system
      requestBody:
        description: Details for the new case + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CourtCaseRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CourtCaseResponse'
        '400':
          description: Case(s) creation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
      x-codegen-request-body-name: caseRequest
  /casemanagement/v1/_update:
    post:
      tags:
        - CaseManagementService
      summary: update case requests.
      requestBody:
        description: Details for the new case(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CaseManagementRequest
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CaseManagementResponse
        '400':
          description: Case(s) updation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
      x-codegen-request-body-name: caseRequest
  /casemanagement/v1/_exists:
    post:
      tags:
        - CaseManagementService
      summary: check if a specific case exists by using case number
      requestBody:
        description: Details for the case(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CaseSearchRequest
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) search successfully
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/CaseExistsResponse
        '400':
          description: Search failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorResponse
  /casemanagement/v1/_search:
    post:
      tags:
        - CaseManagement
      summary: Search for cases
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseSearchRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with cases matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseManagementResponse'
        '400':
          description: Case search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /case/witness/v1/_create:
    post:
      tags:
        - Witness
      summary: Map an individual as a witness to the case
      description: |
        API to map a new individual as witness in the case
      requestBody:
        description: Details for the witness + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/WitnessRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WitnessResponse'
        '400':
          description: Witness creation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes  
  /case/witness/v1/_delete:
    post:
      tags:
        - Witness
      summary: Remove the mapping of individual(s) as a witness to the case
      description: |
        API to remove an individual as witness in the case
      requestBody:
        description: Details for the witness + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/WitnessRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WitnessResponse'
        '400':
          description: Witness updation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    CaseManager:
      type: object
      required: [tenantId]
      properties:
        id:
          type: string
          format: uuid
          description: This id is autogenerated id of the case. It is the primary key
          readOnly: true
          minLength: 36
          maxLength: 36
        tenantId:
          type: string
          description: This is tenantId of the case based on the state.
          minLength: 2
          maxLength: 64
        case:
          type: object
          description: The case object containing all the case registry details
          $ref: './components/schemas/Case'
        workflow:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
        documents:
          type: array
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        additionalDetails:
          type: object
          description: >-
            This field is meant to hold any extra information that we want to
            store for a case.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    
    Witness:
      type: object
      required: [tenantId, userID, caseId]
      properties:
        id:
          type: string
          description: UUID of the record
          format: uuid
          minLength: 36
          maxLength: 36
          readOnly: true
        caseId:
          type: string
          description: >-
            Case UUID from the case registry.
        individualID:
          type: string
          description: Individual/user who is appearing as witness in the case.
        remarks:
          type: string
          description: Free form field to store relevance of witness to a case etc..
        isActive:
          type: boolean
          description: Flag for soft delete
        documents:
          type: array
          description: This can be used to store any documents related to the witness
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information to be stored as
            part of this entity.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
   
    WitnessRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Witness'
    WitnessResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Witness'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
    CaseManagementRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/CourtCase'
    CaseManagementResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/CourtCase'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
    
    CaseSearchRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/CaseCriteria'
    
    CaseExistsResponse:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/CaseExistsResponse'

    CaseCriteria:
      type: object
      properties:
        cnrNumber:
          type: string
        filingNumber:
          type: string
        exists:
          description: True if the case exists. False otherwise
          type: boolean

