openapi: 3.0.0
info:
  title: Case registry
  description: |
    This API specification defines a Case registry.
  version: 1.0.0
tags:
  - name: Case
    description: APIs related to the case registry
paths:
  /case/v1/_create:
    post:
      tags:
        - Case
      summary: Create new case in the registry
      description: |
        Creates a new case in the case registry
      requestBody:
        description: Details for the new court case + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with case groups created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseResponse'
        '400':
          description: Court case creation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /case/v1/_update:
    post:
      tags:
        - CourtCase
      summary: Update a court case
      description: |
        API to update a case registry 
      requestBody:
        description: Details for updating all updatable fields in the court case + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with court case details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseResponse'
        '400':
          description: Case group updation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    Case:
      description: Case registry
      required:
        - tenantId
        - filingDate
        - caseCategory
        - statutesAndSections
        - litigants
      oneOf:
        - required: [filingNumber, caseNumber]
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: This id is autogenerated id of the case. It is the primary key
          readOnly: true
          minLength: 36
          maxLength: 36
        tenantId:
          type: string
          description: This is tenantId where the system is implemented. 
          minLength: 2
          maxLength: 64
        resolutionMechanism:
          type: string
          description: >-
            The mechanism used for dispute resolution. These can be e-courts,
            Lok Adalats or some other entity. Values to be defined in master
            data. The value stored in this field should be a master data ID.
          example: COURT, ADR.MEDIATION, ADR.CONCILIATION, ODR.ARBITRATION, Lok Adalat
          minLength: 2
          maxLength: 128
        caseTitle:
          type: string
          description: A simple one-liner summary title used to refer to the case.
          minLength: 2
          maxLength: 512
        caseDescription:
          type: string
          description: Description/summary/prayer for relief
          minLength: 2
          maxLength: 2500
        filingNumber:
          type: string
          description: The formatted number given at filing time. When a case gets admitted, it is assigned a case number. In some cases, this may not be applicable.
          minLength: 2
          maxLength: 64
        caseNumber:
          type: string
          description: >-
            This refers to the case number record (CNR). This is generated after a case is admitted by the judge with/without an admission hearing. The case number format is different from the filing number format.
          minLength: 2
          maxLength: 64
        courtId:
          type: string
          description: >-
            The court or other ADR entity ID that will be trying/hearing the
            case. In the case of e-courts, it will be courtId.
          minLength: 2
          maxLength: 64
        benchId:
          type: string
          description: >-
            The bench a case is assigned to. A court has multiple benches and
            each bench can comprise of one or more arbitrators. The
            relationships to be defined in master data. The unique master data
            ID for a bench is stored here. 
          minLength: 2
          maxLength: 64
        judgeId:
          type: string
          description: >-
            Employee ID of the individual Judge assigned to the case. Bench or
            judge is assigned depending on the court/case type. 
        linkedCases:
          type: array
          description: Case numbers of related cases - child cases, appealed case etc
          items:
            $ref: '#/components/schemas/LinkedCase'
        filingDate:
          type: string
          format: date
          description: >-
            Date of case filing in epoch time. This is the date when the case
            entered the judicial system.
          example: 1709542147
        caseCategory:
          type: string
          description: Case category from master data
          example: CIVIL, CRIMINAL
          minLength: 2
          maxLength: 64
        caseType:
          type: string
          description: isFresh or appeal or any other case type as required
          example: FRESH, APPELLATE etc..
          minLength: 2
          maxLength: 64
        statutesAndSections:
          type: array
          description: >-
            The legal provisions -- acts/sections/subsections -- under which a
            case is filed
          items:
            $ref: '#/components/schemas/StatuteSection'
        litigants:
          type: array
          items:
            $ref: '#/components/schemas/Party'
          minItems: 1
        representatives:
          type: array
          items:
            $ref: '#/components/schemas/AdvocateMapping'
        status:
          type: string
          description: >-
            The current status of the case as pulled from the Workflow service.
            Workflow service will hold the entire history of hte case.
        documents:
          type: array
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        remarks:
          type: string
          description: This field can hold any other additional remarks about the case
        additionalDetails:
          type: object
          description: >-
            This field is meant to hold any extra information that we want to
            store for a case.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    
    StatuteSection:
      type: object
      description: >-
        Holds the statute ID and the corresponding section & subsections
        applicable to the case. 
      required: [tenantId, statuteId]
      properties:
        id:
          type: string
          description: Read only UUID
          readOnly: true
          format: uuid
          minLength: 2
          maxLength: 64
        tenantId:
          type: string
          description: This is tenantId of the case.
          minLength: 2
          maxLength: 64
        statutes:
          type: string
          description: >-
            The statute ID from master data. 
        sections:
          type: array
          items:
            type: string
        subsections:
          type: array
          description: >-
            Holds an array of subsections under which this case is filed. This
            can be a master or a free form text entry field.
          items:
            type: string
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information to be stored as
            part of this entity.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    LinkedCase:
      type: object
      properties:
        id:
          type: string
          description: UUID in the system
          format: uuid
        relationshipType:
          type: string
          example: PARENT, CHILD, PRIOR_APPEAL
        caseNumbers:
          type: array
          items:
            type: string
        isActive:
          type: boolean
          description: Field to indicate soft delete of record
        documents:
          type: array
          description: This can be used to store any documents related to the linked cases
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information to be stored as
            part of this entity.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    
    AdvocateMapping:
      type: object
      required: [tenantId]
      oneOf:
        - required: [filingNumber, caseNumber]
      properties:
        id:
          type: string
          description: autogenerated id of the case. It is the primary key.
          minLength: 2
          maxLength: 64
          readOnly: true
        tenantId:
          type: string
          description: The tenant where this case is operational currently
        advocateId:
          type: string
          description: The advocate ID associated with the case
        caseId:
          type: string
          description: The CNR number of the case available post admission in case the advocate is involved only post admission.
        representing:
          type: array
          items:
            $ref: '#/components/schemas/Party'
          minItems: 1
        isActive:
          type: boolean
          description: Field used for soft delete of records. Will be false if this entity
            is not active within the system.
          default: true
        documents:
          type: array
          description: >-
            This can be used to store the Vakalathnama and other agreements
            between advocate and party.
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any extra fields that are not captured as first class fields can be
            stored here as key/value pairs. Implementation specific.
    
    Party:
      type: object
      properties:
        id:
          type: string
          description: autogenerated id of the case. It is the primary key.
          minLength: 2
          maxLength: 128
          readOnly: true
        tenantId:
          type: string
          description: The tenant where this case is operational
        referenceId:
          type: string
          description: Refers to the case ID
        partyCategory:
          type: string
          description: >-
            Is Individual or organisation or something else. Master data ID to
            be stored here.
          example: INDIVIDUAL, ORGANISATION
        organisationID:
          type: string
          description: >-
            If the party is an organiation, refers to the org ID which will
            contain details of the org
        userId:
          type: string
          description: >-
            The user ID of the complainant. In case party is of type org, this
            is the person representing the company in the case. This entity
            holds all the details of the user including their name, address,
            contact etc..
        partyType:
          type: string
          description: >-
            This field holds imformation about type of party (name spaced Master
            Data).
          example:
            - complainant.primary
            - complainant.additional
            - respondent.primary
        isActive:
          type: boolean
          description: >-
            Field used for soft delete of records. Will be false if this entity
            is not active within the system.
          default: true
        documents:
          type: array
          description: >-
            This can be used to store the Vakalathnama and other agreements
            between advocate and party.
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any extra fields that are not captured as first class fields can be
            stored here as key/value pairs. Implementation specific.
      required:
        - tenantId
        - advocateId
        - referenceId
        - partyCategory
      oneOf:
        - required:
            - userId
            - organisationID
   
    CaseRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Case'
    CaseResponse:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        cases:
          type: array
          items:
            $ref: '#/components/schemas/Case'
    
    CaseExistsRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/CaseCriteria'
    
    CaseExistsResponse:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/CaseExists'

    CaseCriteria:
      type: object
      properties:
        cnrNumber:
          type: string
        filingNumber:
          type: string
    
    CaseExists:
      type: object
      properties:
        cnrNumber:
          type: string
        filingNumber:
          type: string
        exists:
          type: boolean

