openapi: 3.0.0
info:
  title: Evidence
  description: |
   API specs for uploading artifacts/marking as evidence etc..Chain of custody and other details of evidence history are not handled in this version. Artifacts can be uploaded voluntarily or because of an order or hearing. They can be marked as "EVIDENCE" by the judge anytime during the course of a case. This is modeled as workflow.
  version: 1.0.0
tags:
  - name: Evidence
    description: APIs required to upload digital artifacts for evidence consideration
  
paths:
  /artifacts/v1/_create:
    post:
      tags:
        - Evidence
      summary: Upload artifacts that could potentially be accepted as evidence
      description: |
        API used to create a new artifact that could become evidence in a case
      requestBody:
        description: Details for the artifact + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EvidenceRequest'
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EvidenceResponse'
        '400':
          description: Case(s) creation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
      x-codegen-request-body-name: caseRequest
  /artifacts/v1/_update:
    post:
      tags:
        - Evidence
      summary: update case requests.
      requestBody:
        description: Details for the new case(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/EvidenceRequest
        required: true
      responses:
        '201':
          description: ReponseInfo with case(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/EvidenceResponse
        '400':
          description: Case(s) updation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes

components:
  schemas:
    Artifact:
      required: [tenantId]
      oneOf:
        - required: [filingNumber, cnrNumber]
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: This id is autogenerated id of the artifact. It is the primary key
          readOnly: true
          minLength: 2
          maxLength: 64
        tenantId:
          type: string
          description: This is tenantId of the case based on the state.
        artifactNumber:
          type: string
          description: Identification number assigned when an artifact is uploaded
          minLength: 2
          maxLength: 64
        evidenceNumber:
          type: string
          description: Formatted evidence number assigned after evidence is accepted by the deciding authority.
          minLength: 2
          maxLength: 64
        externalRefNumber:
          type: string
          description: Reference to a physical artifact or other evidence collected during the course of an investigation
          minLength: 2
          maxLength: 128
        cnrNumber:
          type: string
          description: Reference to the case number record of the CourtCase registry
        hearing:
          type: string
          description: Reference to the hearing where evidence could've been introduced.
        order:
          type: string
          description: Reference to the order that led to uploading this artifact
        mediaType:
          type: string
          description: Represents the type of artifact, such as audio, video, document, etc..
          example: AUDIO, VIDEO, DOC
        artifactType:
          type: string
          description: Represents the legal classification of the artifact, such as sworn statement, affidavit, testimony, etc.
          example: AFFIDAVIT, DEPOSITION, SWORN_STATEMENT, OTHER etc.. 
        sourceID:
          type: string
          description: The user ID who provided this artifact.
        sourceType:
          type: string
          example: COMPLAINANT, RESPONDENT, WITNESS, OTHER
        createdDate:
          type: integer
          format: date
          description: Date this artifact was uploaded
        onBehalfOf:
          type: array
          items:
            type: string
        isActive:
          type: boolean
          description: Field to indicate soft delete of records
        status:
          type: string
          description: >-
            The current status of the case as pulled from the Workflow service.
            Workflow service will hold the entire history of the case.
        files:
          type: array
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        remarks:
          type: string
          description: Field to hold extra info about the artifact
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information that we want to
            store for a case.
        auditdetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        workflow:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
    
   
    EvidenceRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/Artifact'
    EvidenceResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/Artifact'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination

