name: dristi workflow
on:
  push:
    branches:
      - dev_backend_order_bis
  workflow_dispatch:
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io
      - name: build artifact for case
        run: mvn -B -f backend/case/pom.xml clean install
      - name: Build and Push Docker image for order
        run: |
          docker build --build-arg WORK_DIR="backend/order" -t pucar_order:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker tag pucar_order:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_order:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_order:v1.0.0-${{ github.sha }}
      - name: Build and Push Docker image for order_DB
        run: |
          docker build  -t pucar_order_db:v1.0.0-${{ github.sha }} -f  Dockerfile .
           docker tag pucar_order_db:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_order_db:v1.0.0-${{ github.sha }}
           docker push pucardev.azurecr.io/pucar_order_db:v1.0.0-${{ github.sha }}
        working-directory: backend/order/src/main/resources/db
      - name: Trigger Deployment Pipeline
        run: |
         curl -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
         https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/dev.yaml/dispatches \
         -d '{"ref":"Dev-0"}'
