name: dristi workflow
on:
  push:
    branches:
      - user-registration-flow
  workflow_dispatch:
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build Package
        run: mvn -B clean install -f backend/advocate
      - name: Sonarqube Scan
        run: mvn -f backend/advocate/pom.xml sonar:sonar -Dsonar.projectKey=pucardotorg -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectBaseDir=backend/advocate
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io

      - name: Build and Push Docker image for digit-ui
        run: |
         docker build  -t digit-ui:v1.0.0-${{ github.sha }} -f  web/docker/Dockerfile .
         docker tag digit-ui:v1.0.0-${{ github.sha }} pucardev.azurecr.io/digit-ui:v1.0.0-${{ github.sha }}
         docker push pucardev.azurecr.io/digit-ui:v1.0.0-${{ github.sha }}
        working-directory: frontend/micro-ui
      - name: trigger deployment pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/dev.yaml/dispatches \
          -d '{"ref":"Dev-0"}'
